### ISSUE TITLE
As a user, I need to be able to search for specific expenses and navigate through my expense history efficiently.

### ISSUE THREAD

**Issue by nathan-cool** [nathan-cool/Expenses#17]
## Task: Implement Search and Pagination for Expenses

**As a user, I need to be able to search for specific expenses and navigate through my expense history efficiently.**

### Acceptance Criteria

- [x] 	User can search for expenses using criteria such as amount, date, category, or description
- [x] 	Search results are displayed in a paginated format
- [x] 	User can navigate through different pages of expenses
- [x] 	Only expenses belonging to the logged-in user are displayed in search results and pagination
