### ISSUE TITLE
As a user, I need to be able to set and update my preferences so that the application is tailored to my needs.

### ISSUE THREAD

**Issue by nathan-cool** [nathan-cool/Expenses#18]
## Task: Implement User Preferences Management

**As a user, I need to be able to set and update my preferences so that the application is tailored to my needs.**

### Acceptance Criteria

- [x] 	User can set their preferred currency
- [x] 	User can update their currency preference at any time
- [x]   All expenses are displayed in the user's preferred currency
- [x] 	Currency preferences are loaded from a JSON file and presented as options to the user
