### ISSUE TITLE
As a user, I need the application to be responsive so that I can access and use it on various devices.

### ISSUE THREAD

**Issue by nathan-cool** [nathan-cool/Expenses#20]
## Task: Ensure Application Responsiveness

**As a user, I need the application to be responsive so that I can access and use it on various devices.**

### Acceptance Criteria

- [x] 	 The application is fully functional on desktop browsers
- [x] 	 The application is fully functional on mobile devices (e.g., iPhone SE, iPhone X, iPhone 14, iPhone 6)
- [x] 	 The application is fully functional on tablet devices (e.g., Galaxy Fold)
- [x] 	 All features are accessible and usable across different screen sizes
