### ISSUE TITLE
EPIC: User Authentication and Account Management

### ISSUE THREAD

**Issue by nathan-cool** [nathan-cool/Expenses#21]
# EPIC: User Authentication and Account Management 

As a User I can manage my account so that I can
access and personalize my experience on the platform

- [x] Tasks#12 - USER STORY: User registration #12
- [x] Tasks#3 - USER STORY: User login #3
- [x] Tasks#10 - USER STORY: User logout #10
- [x] Tasks#11 - USER STORY: Set and update preferences #11
