### ISSUE TITLE
EPIC: Expense Tracking Functionality

### ISSUE THREAD

**Issue by nathan-cool** [nathan-cool/Expenses#22]
# EPIC: Expense Tracking Functionality

As a User I can manage my expenses so that I can keep track of my spending and financial activities

- [x] Tasks#13 - USER STORY: Add an expense #13
- [x] Tasks#14 -  USER STORY: View expenses #14
- [x] Tasks#15 -  USER STORY: Edit expenses #15
- [x] Tasks#16 - USER STORY: Delete an expense #16
- [x] Tasks#5 - USER STORY: Search for specific expenses #5
