### ISSUE TITLE
EPIC: Application Development and Deployment

### ISSUE THREAD

**Issue by nathan-cool** [nathan-cool/Expenses#23]
# EPIC: Application Development and Deployment

As a Developer I can set up and deploy the application so that users can access and use it on various platforms

- [x] Tasks#1 - [USER STORY: Set up project #1
- [x] Tasks#4 -  USER STORY: Deploy project to Heroku #4
- [x] Tasks#6 -  USER STORY: Create base HTML page and structure #6
- [x] Tasks#8 - USER STORY: Create readme file #8
