### ISSUE TITLE
EPIC: User Experience and Interface

### ISSUE THREAD

**Issue by nathan-cool** [nathan-cool/Expenses#24]
# EPIC: User Experience and Interface

As a User I can interact with a responsive and user-friendly interface so that I can effectively use the application across various devices

- [x] Tasks#2 - USER STORY: Make application responsive #2
- [x] Tasks#10 - USER STORY: Provide clear feedback for inputs and errors #10
- [x] Tasks#9 - USER STORY: Implement access control and notifications #9
